// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk47y2r1Na9H8I8fUYCYUCegwAbi-UkNI',
    appId: '1:78844381267:web:bd417d48db2ad3af699ea6',
    messagingSenderId: '78844381267',
    projectId: 'emergency-system-2ae13',
    authDomain: 'emergency-system-2ae13.firebaseapp.com',
    databaseURL: 'https://emergency-system-2ae13-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-system-2ae13.firebasestorage.app',
    measurementId: 'G-CW1G2FDPXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvfFC9gxUsqPmsYttLqGn97AUekiOb9lk',
    appId: '1:78844381267:android:107c6e42f8abf0e2699ea6',
    messagingSenderId: '78844381267',
    projectId: 'emergency-system-2ae13',
    databaseURL: 'https://emergency-system-2ae13-default-rtdb.firebaseio.com',
    storageBucket: 'emergency-system-2ae13.firebasestorage.app',
  );
}

